# Generated by Django 3.2.21 on 2023-09-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horário_chegada', models.DateTimeField(verbose_name='horario chegada')),
                ('horario_saida', models.DateTimeField(verbose_name='horario saida')),
                ('valor_diaria', models.FloatField(verbose_name='valor diaria')),
                ('valor_pago', models.FloatField(verbose_name='valor pago')),
                ('valor_a_pagar', models.FloatField(verbose_name='valor a pagar')),
                ('modalidade_pag', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_usuario', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date acesso')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.CharField(max_length=20)),
                ('id_curso', models.CharField(max_length=20)),
                ('id_materia', models.CharField(max_length=20)),
                ('id_professor', models.CharField(max_length=20)),
                ('id_turma', models.CharField(max_length=20)),
                ('sessao_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.sessao')),
            ],
        ),
    ]
